### ISSUE TITLE
Upload rate stays around the same as standard google drive uploader due to limitations in the Google API

### ISSUE THREAD

**Issue by shillshocked** [hundeboll/grind#2]
ERROR: upload failed: <HttpError 403 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&alt=json returned "User rate limit exceeded">

I get these a lot. My upload bandwidth is 5+ MiB/s, and I get less than 2 MiB/s on average, which is about the same upload rate you would get with the standard upload process. It did spurt to max speed for a while until it hit the API limits.

**Comment by hundeboll** [comment]
I guess Google decided to induce a lower limit. Not much one can do about that.
